/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./../layout/components/AppMain/index.vue')['default']
    Aside: typeof import('./../layout/components/Aside/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Footer: typeof import('./../layout/components/Footer/index.vue')['default']
    Hamburger: typeof import('./../components/Hamburger/index.vue')['default']
    Header: typeof import('./../layout/components/Header/index.vue')['default']
    Layout: typeof import('./../layout/index.vue')['default']
    NavbarLeft: typeof import('./../layout/components/Header/components/NavbarLeft.vue')['default']
    NavbarRight: typeof import('./../layout/components/Header/components/NavbarRight.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TestCom: typeof import('./../components/testCom.vue')['default']
  }
}
