/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./../layout/components/AppMain/index.vue')['default']
    Aside: typeof import('./../layout/components/Aside/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: (typeof import("element-plus/es"))["ElAvatar"]
    ElButton: (typeof import("element-plus/es"))["ElButton"]
    ElCard: (typeof import("element-plus/es"))["ElCard"]
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: (typeof import("element-plus/es"))["ElDropdown"]
    ElDropdownItem: (typeof import("element-plus/es"))["ElDropdownItem"]
    ElDropdownMenu: (typeof import("element-plus/es"))["ElDropdownMenu"]
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: (typeof import("element-plus/es"))["ElForm"]
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"]
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: (typeof import("element-plus/es"))["ElIcon"]
    ElInput: (typeof import("element-plus/es"))["ElInput"]
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: (typeof import("element-plus/es"))["ElRow"]
    ElScrollbar: (typeof import("element-plus/es"))["ElScrollbar"]
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"]
    Footer: typeof import('./../layout/components/Footer/index.vue')['default']
    Header: typeof import('./../layout/components/Header/index.vue')['default']
    IEpAvatard: (typeof import("~icons/ep/avatard"))["default"]
    IEpEdit: (typeof import("~icons/ep/edit"))["default"]
    IEpFold: (typeof import("~icons/ep/fold"))["default"]
    IEpHelp: (typeof import("~icons/ep/help"))["default"]
    IEpInfoFilled: (typeof import("~icons/ep/info-filled"))["default"]
    IEpSuccessFilled: (typeof import("~icons/ep/success-filled"))["default"]
    IEpWarningFilled: (typeof import("~icons/ep/warning-filled"))["default"]
    IEpWarnTriangleFilled: (typeof import("~icons/ep/warn-triangle-filled"))["default"]
    Layout: typeof import('./../layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCom: typeof import('./../components/testCom.vue')['default']
  }
}
